apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtual-service-{{ .Values.application }} 
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/default-gateway
  http:
  - match:
    - uri:
        prefix: /{{ .Values.application }} 
    route:
    - destination:
        host: {{ .Values.application }}.default.svc.cluster.local
        port:
          number: 80